# Generated by Django 5.0.6 on 2025-07-03 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Short biography of the user.', null=True)),
                ('location', models.CharField(blank=True, help_text='Location of the user.', max_length=50, null=True)),
                ('tel', models.CharField(blank=True, help_text='Telephone number of the user.', max_length=15, null=True)),
                ('working_hours', models.CharField(blank=True, help_text='Working hours of the user.', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the profile was created.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
