# Generated by Django 5.0.6 on 2025-07-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='title',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
