# Generated by Django 5.0.6 on 2025-07-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offer_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='min_delivery_time',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='min_price',
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='offer_type',
            field=models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], help_text='Type of the offer detail (Basic, Standard, Premium)', max_length=20),
        ),
    ]
